package org.javabase.apps.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InsClass generated by hbm2java
 */
@Entity
@Table(name = "class_on_shift")
public class ClassOnShift implements java.io.Serializable {

	private static final long serialVersionUID = 5752897246938401293L;
	private Integer shiftClaId;
	private Integer classId;
    private Integer insShiftId;
    private Date entryDate;
    private Date updateDate;
    private Integer entryUser;
    private Integer updateUser;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "shift_cla_id", unique = true, nullable = false)
    public Integer getShiftClaId() {
    	return shiftClaId;
    }
    
    public void setShiftClaId(Integer shiftClaId) {
    	this.shiftClaId = shiftClaId;
    }
  
    
    @Column(name = "class_id")
    public Integer getClassId() {
        return this.classId;
    }


	public void setClassId(Integer classId) {
        this.classId = classId;
    }

    @Column(name = "ins_shift_id")
    public Integer getInsShiftId() {
        return this.insShiftId;
    }

    public void setInsShiftId(Integer insShiftId) {
        this.insShiftId = insShiftId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "entry_date", length = 19)
    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 19)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "entry_user")
    public Integer getEntryUser() {
        return this.entryUser;
    }

    public void setEntryUser(Integer entryUser) {
        this.entryUser = entryUser;
    }

    @Column(name = "update_user")
    public Integer getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

}
