package org.javabase.apps.entity;
// Generated Jan 10, 2017 12:47:22 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GardianInfo generated by hbm2java
 */
@Entity
@Table(name = "gardian_info", catalog = "jschool"
)
public class GardianInfo implements java.io.Serializable {

	private static final long serialVersionUID = -5860616562476643459L;
	private Integer gardianInfoId;
    private Integer userInfoId;
    private Integer studentId;
    private String relation;
    private String homeDistrict;
    private String nidNo;
    private String gardianName;
    private String profession;
    private String jobPosition;
    private String company;
    private String address;
    private String officeAddress;
    private String officeContact;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "gardian_info_id", unique = true, nullable = false)
    public Integer getGardianInfoId() {
        return this.gardianInfoId;
    }

    public void setGardianInfoId(Integer gardianInfoId) {
        this.gardianInfoId = gardianInfoId;
    }

    @Column(name = "user_info_id")
    public Integer getUserInfoId() {
        return this.userInfoId;
    }

    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    @Column(name = "student_id")
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @Column(name = "relation", length = 45)
    public String getRelation() {
        return this.relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    @Column(name = "home_district", length = 45)
    public String getHomeDistrict() {
        return this.homeDistrict;
    }

    public void setHomeDistrict(String homeDistrict) {
        this.homeDistrict = homeDistrict;
    }

    @Column(name = "nid_no", length = 45)
    public String getNidNo() {
        return this.nidNo;
    }

    public void setNidNo(String nidNo) {
        this.nidNo = nidNo;
    }

    @Column(name = "gardian_name", length = 45)
    public String getGardianName() {
        return this.gardianName;
    }

    public void setGardianName(String gardianName) {
        this.gardianName = gardianName;
    }

    @Column(name = "profession", length = 45)
    public String getProfession() {
        return this.profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    @Column(name = "job_position", length = 45)
    public String getJobPosition() {
        return this.jobPosition;
    }

    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition;
    }

    @Column(name = "company", length = 45)
    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Column(name = "address", length = 45)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "office_address", length = 45)
    public String getOfficeAddress() {
        return this.officeAddress;
    }

    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    @Column(name = "office_contact", length = 45)
    public String getOfficeContact() {
        return this.officeContact;
    }

    public void setOfficeContact(String officeContact) {
        this.officeContact = officeContact;
    }

}
