package org.javabase.apps.entity;
// Generated Jan 10, 2017 12:47:22 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GenderName generated by hbm2java
 */
@Entity
@Table(name = "gender_name")
public class GenderName implements java.io.Serializable {

	private static final long serialVersionUID = -549598643119349098L;
	private Integer genderId;
    private String genderName;
    private String genderCode;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "gender_id", unique = true, nullable = false)
    public Integer getGenderId() {
        return this.genderId;
    }

    public void setGenderId(Integer genderId) {
        this.genderId = genderId;
    }

    @Column(name = "gender_name", length = 45)
    public String getGenderName() {
        return this.genderName;
    }

    public void setGenderName(String genderName) {
        this.genderName = genderName;
    }

    @Column(name = "gender_code", length = 5)
    public String getGenderCode() {
        return this.genderCode;
    }

    public void setGenderCode(String genderCode) {
        this.genderCode = genderCode;
    }

}
