package org.javabase.apps.entity;
// Generated Jan 10, 2017 12:47:22 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GivenRole generated by hbm2java
 */
@Entity
@Table(name = "given_role", catalog = "jschool"
)
public class GivenRole implements java.io.Serializable {

	private static final long serialVersionUID = -8096810439541361394L;
	private Integer givenRoleId;
    private Integer insSysRoelId;
    private Integer roleId;
    private Integer userId;
    private Integer roleGivenUser;
    private Date updateDate;
    private String entryDate;
    private Integer entryUser;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "given_role_id", unique = true, nullable = false)
    public Integer getGivenRoleId() {
        return this.givenRoleId;
    }

    public void setGivenRoleId(Integer givenRoleId) {
        this.givenRoleId = givenRoleId;
    }

    @Column(name = "ins_sys_roel_id")
    public Integer getInsSysRoelId() {
        return this.insSysRoelId;
    }

    public void setInsSysRoelId(Integer insSysRoelId) {
        this.insSysRoelId = insSysRoelId;
    }

    @Column(name = "role_id")
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Column(name = "user_id")
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "role_given_user")
    public Integer getRoleGivenUser() {
        return this.roleGivenUser;
    }

    public void setRoleGivenUser(Integer roleGivenUser) {
        this.roleGivenUser = roleGivenUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 19)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "entry_date", length = 45)
    public String getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    @Column(name = "entry_user")
    public Integer getEntryUser() {
        return this.entryUser;
    }

    public void setEntryUser(Integer entryUser) {
        this.entryUser = entryUser;
    }

}
