package org.javabase.apps.entity;
// Generated Jan 10, 2017 12:47:22 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsCatagoryType generated by hbm2java
 */
@Entity
@Table(name = "ins_catagory_type")
public class InsCatagoryType implements java.io.Serializable {

	private static final long serialVersionUID = -7940768181909375360L;
	private Integer nsCatagoryTypeIdi;
    private String catagoryName;
    private String catagoryCode;
    private String comments;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ns_catagory_type_idi", unique = true, nullable = false)
    public Integer getNsCatagoryTypeIdi() {
        return this.nsCatagoryTypeIdi;
    }

    public void setNsCatagoryTypeIdi(Integer nsCatagoryTypeIdi) {
        this.nsCatagoryTypeIdi = nsCatagoryTypeIdi;
    }

    @Column(name = "catagory_name", length = 45)
    public String getCatagoryName() {
        return this.catagoryName;
    }

    public void setCatagoryName(String catagoryName) {
        this.catagoryName = catagoryName;
    }

    @Column(name = "catagory_code", length = 10)
    public String getCatagoryCode() {
        return this.catagoryCode;
    }

    public void setCatagoryCode(String catagoryCode) {
        this.catagoryCode = catagoryCode;
    }

    @Column(name = "comments", length = 100)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

}
