package org.javabase.apps.entity;
// Generated Jan 10, 2017 12:47:22 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentInfo generated by hbm2java
 */
@Entity
@Table(name = "student_info", catalog = "jschool"
)
public class StudentInfo implements java.io.Serializable {

    private Integer studentId;
    private String userInfoId;
    private String session;
    private Integer classId;
    private Integer secId;
    private Integer classRoel;
    private Integer stuTrackingId;
    private Integer shitId;
    private Integer upgradeClass;
    private String father;
    private String mother;
    private String homeDistrict;
    private String presentAddress;
    private String permaAddress;
    private String birthId;
    private String image;
    private String comment;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "student_id", unique = true, nullable = false)
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @Column(name = "user_info_id", length = 45)
    public String getUserInfoId() {
        return this.userInfoId;
    }

    public void setUserInfoId(String userInfoId) {
        this.userInfoId = userInfoId;
    }

    @Column(name = "session", length = 45)
    public String getSession() {
        return this.session;
    }

    public void setSession(String session) {
        this.session = session;
    }

    @Column(name = "class_id")
    public Integer getClassId() {
        return this.classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    @Column(name = "sec_id")
    public Integer getSecId() {
        return this.secId;
    }

    public void setSecId(Integer secId) {
        this.secId = secId;
    }

    @Column(name = "class_roel")
    public Integer getClassRoel() {
        return this.classRoel;
    }

    public void setClassRoel(Integer classRoel) {
        this.classRoel = classRoel;
    }

    @Column(name = "stu_tracking_id")
    public Integer getStuTrackingId() {
        return this.stuTrackingId;
    }

    public void setStuTrackingId(Integer stuTrackingId) {
        this.stuTrackingId = stuTrackingId;
    }

    @Column(name = "shit_id")
    public Integer getShitId() {
        return this.shitId;
    }

    public void setShitId(Integer shitId) {
        this.shitId = shitId;
    }

    @Column(name = "upgrade_class")
    public Integer getUpgradeClass() {
        return this.upgradeClass;
    }

    public void setUpgradeClass(Integer upgradeClass) {
        this.upgradeClass = upgradeClass;
    }

    @Column(name = "father", length = 45)
    public String getFather() {
        return this.father;
    }

    public void setFather(String father) {
        this.father = father;
    }

    @Column(name = "mother", length = 45)
    public String getMother() {
        return this.mother;
    }

    public void setMother(String mother) {
        this.mother = mother;
    }

    @Column(name = "home_district", length = 45)
    public String getHomeDistrict() {
        return this.homeDistrict;
    }

    public void setHomeDistrict(String homeDistrict) {
        this.homeDistrict = homeDistrict;
    }

    @Column(name = "present_address", length = 45)
    public String getPresentAddress() {
        return this.presentAddress;
    }

    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }

    @Column(name = "perma_address", length = 45)
    public String getPermaAddress() {
        return this.permaAddress;
    }

    public void setPermaAddress(String permaAddress) {
        this.permaAddress = permaAddress;
    }

    @Column(name = "birth_id", length = 45)
    public String getBirthId() {
        return this.birthId;
    }

    public void setBirthId(String birthId) {
        this.birthId = birthId;
    }

    @Column(name = "image", length = 45)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "comment", length = 45)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
